image:
  - Visual Studio 2017

environment:
  matrix:
  - platform: x64
    ARCH: x86-64
    CFLAGS: -m64 -static -I"/opt/llvm50/include/" -L"/opt/llvm50/lib/"
    PATH: C:\msys64\mingw64\bin\;C:\msys64\usr\bin\;$(PATH)
    PACKAGES: mingw-w64-x86_64-toolchain mingw-w64-x86_64-g++ mingw-w64-x86_64-cmake

skip_non_tags: true

branches:
  onpply:
    - master
    - "/^v\\d+(\\.\\d+)+$/"

install:
  - >
    sh -c "
    pacman -S --needed --noconfirm base-devel %PACKAGES%
    && wget -O /llvm.tar.gz http://bodge.borodust.org/files/llvm50.tar.gz
    && cd / && tar -xf llvm.tar.gz .
    "

build_script:
  - set TARGET_ARTIFACT=c2ffi-windows-%ARCH%.zip
  - >
    sh -c "
    export LLVM_DIR=/opt/llvm50/lib/cmake/
    && mkdir build
    && cd build
    && cmake -G "Unix Makefiles" ..
    && cmake --build .
    "

before_deploy:
  - mv %APPVEYOR_BUILD_FOLDER%\build\bin\c2ffi.exe %APPVEYOR_BUILD_FOLDER%\%TARGET_ARTIFACT%

artifacts:
  - path: $(TARGET_ARTIFACT)
    name: target_artifact

deploy:
  provider: GitHub
  release: $(APPVEYOR_REPO_TAG_NAME)
  tag: $(APPVEYOR_REPO_TAG_NAME)
  description: $(APPVEYOR_REPO_COMMIT_MESSAGE)
  auth_token:
    secure: Z5XWjDOBlCrmfz3SQAjnLKtdgI5B2b/owJhRPNWYGrI+qwVNbBc4cZiroBZReWP7
  artifact: target_artifact
  force_update: true
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
